### ISSUE TITLE
Possible to load locally stored image?

### ISSUE THREAD

**Issue by andrewcking** [mzelzoghbi/ZGallery#22]
Is it possible to load local images with zgallery? Passing in file paths does not seem to work (such as:  file:///storage/emulated/0/foo.jpg), though I know glide supports loading local files.

**Comment by andrewcking** [comment]
I should have worked at it a bit more. I was able to do it using the following string notation and passing that instead of URLs:

    Environment.getExternalStorageDirectory() + "/" + "foo.jpg"

**Comment by veer3383** [comment]
How did u get this working? can you please explain little more?
i tried` imagesList.add(Environment.getExternalStorageDirectory() + "/" + "foo.jpg");`
doesnt seem to load

**Comment by andrewcking** [comment]
Perhaps you need to add the file storage permission? ZGallery doesn't request it by default since they are loading from the web in the sample. Check your AndroidManifest.xml and add 

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

if it is not already there.

**Comment by veer3383** [comment]
Yes i had already added `READ_EXTERNAL_STORAGE` permission, now i have added `WRITE_EXTERNAL_STORAGE` too.. still i am not able to get it working, the only change that i have done in sample project is this..
```
 ArrayList<String> imagesList = new ArrayList<>();
        imagesList.add(Environment.getExternalStorageDirectory() + "/" + "foo.jpg");
        imagesList.add("http://static0.passel.co/wp-content/uploads/2016/08/05095154/tumblr_oawfisUmZo1u7ns0go1_500.jpg");
```

i do have foo.jpg at specified location at `/sdcard/foo.jpg`
